[package]
name = "cam_producer"
version = "0.1.0"
authors = ["Darius Bakunas-Milanowski <bakunas@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
rdkafka = "0.21.0"
log = "0.4.6"
env_logger = "0.6.1"
tokio = "0.1.21"